# -*- coding: utf-8 -*-

from . import ft_import
from . import purchase_order
from . import purchase_requisition
from . import product_template
from . import sale_report
from . import purchase_report
from . import res_partner
from . import res_company
from . import account_tax
from . import account_move
from . import ft_shipping_companies
from . import ft_delay_fee
from . import ft_associated_expenses
from . import ft_ports
from . import ft_duty
from . import ft_agreement
from . import ft_certificate_type
from . import ft_certificate
from . import ft_novelty_type
from . import ft_containers
from . import ft_capacities_container
from . import ft_storage
from . import ft_vigilance_fee
from . import ft_import_routes
from . import ft_label
from . import ft_binnacle
from . import ft_import_container
from . import ft_forecast_product
from . import ft_forecast
from . import res_config_settings
